print('문제 1')
str1=input("문자열 입력>> ")
n=len(str1)
print("참조할 첨자: ",0," ~ ",n-1)
a=int(input("참조할 첨자 입력>> "))
print("문자열: ",str1,", 길이: ",n,sep='')
print("참조 문자: ",str1[a]);

print('문제 2')
str2=input("다섯 문자 이상의 문자열 입력>> ")
print("입력 문자열: ",str2)
print("첫 문자: ",str2[0])
n2=len(str2)
print("마지막 문자: ",str2[n2-1])
print("첫 문자를 제외한 부분 문자열: ",str2[1:])
print("마지막 문자를 제외한 부분 문자열: ",str2[:n2-1])
print("맨 앞과 뒤의 두 문자씩를 제외한 부분 문자열: ",str2[2:n2-2])
print("문자 하나씩을 건너 뛴 부분 문자열: ", str2[::2])
print("역 문자열 ",str2[::-1])
